Repository realme-mt6771-devs/android_device_realme_mt6771-common, pull requests merged in 2022-10, with the labels that each got.

#1 Address denials
  sepolicy/private/system_app.te
  sepolicy/vendor/attributes.te
  sepolicy/vendor/epdg_wod.te
  sepolicy/vendor/file.te
  sepolicy/vendor/file_contexts
  sepolicy/vendor/gmscore_app.te
  sepolicy/vendor/hal_cryptoeng_default.te
  sepolicy/vendor/hal_graphics_composer_default.te
  sepolicy/vendor/hal_wifi_default.te
  sepolicy/vendor/hwservice.te
  sepolicy/vendor/hwservice_contexts
  sepolicy/vendor/init.te
  sepolicy/vendor/mnld.te
  sepolicy/vendor/mtk_agpsd.te
  sepolicy/vendor/mtk_hal_audio.te
  sepolicy/vendor/mtk_hal_camera.te
  sepolicy/vendor/mtk_hal_sensors.te
  sepolicy/vendor/property.te
  sepolicy/vendor/property_contexts
  sepolicy/vendor/surfaceflinger.te
  sepolicy/vendor/system_app.te
  sepolicy/vendor/thermal.te
  sepolicy/vendor/ueventd.te
  sepolicy/vendor/vendor_init.te
Labels: hacktoberfest-accepted

#3 mt6771-common: Drop IORAP props
  system.prop
Labels: enhancement, hacktoberfest-accepted

#5 mt6771-common: Drop non needed interfaces
  mt6771-common.mk
Labels: enhancement, good first issue, hacktoberfest-accepted

#6 mt6771-common: Drop EXTRA VNDK Flag
  mt6771-common.mk
Labels: enhancement, good first issue, hacktoberfest-accepted

#8 mt6771-common: props: Drop useless props
  vendor.prop
Labels: enhancement, good first issue, hacktoberfest-accepted

#7 mt6771-common: init: Update Build fp from `Coral October'22 A13`
  init/init_mt6771.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted
